openapi: "3.0.2"
info:
  title: OBESIFIX 2024 BACK-END
  description: Api specification for obesifix back-end. this endpoint consume from front-end
  version: "2.0"
servers:
  - url: http://localhost:3000
paths:
  /register:
    post:
      tags:
        - "Auth API"
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                age:
                  type: integer
                gender:
                  type: string
                height:
                  type: number
                  multipleOf: 0.01
                weight:
                  type: number
                  multipleOf: 0.01
                activity:
                  type: string
                food_type:
                  type: string

      responses:
        "201":
          description: Success register new user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
  /login/authjwt:
    post:
      tags:
        - "Auth API"
      summary: Login user using email and password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Success login user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /login/google:
    post:
      security:
        - UserGoogleAuth: []
      tags:
        - "Auth API"
      summary: Login user using google account
      responses:
        "200":
          description: "Success login user"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /refresh:
    post:
      tags:
        - "Auth API"
      summary: To renew an expired access token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
      responses:
        "200":
          description: success refresh token
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  statusCode:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      userId:
                        type: string
                      accessToken:
                        type: string

  /logout:
    delete:
      security:
        - UserAuth: []
      tags:
        - "Auth API"
      summary: delete user session
      responses:
        "200":
          description: Success logout user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  statusCode:
                    type: number
                  message:
                    type: string
  /user/{userId}:
    get:
      security:
        - UserAuth: []
      tags:
        - "User API"
      summary: Get user data by user ID
      parameters:
        - name: userId
          in: path
          description: user id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success get data user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  statusCode:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      user_id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      picture:
                        type: string
                      age:
                        type: number
                      gender:
                        type: string
                      height:
                        type: number
                      weight:
                        type: number
                      activity:
                        type: string
                      food_type:
                        type: string
                      created_at:
                        type: string
                      update_at:
                        type: string
    put:
      security:
        - UserAuth: []
      tags:
        - "User API"
      summary: Update user data by user ID
      parameters:
        - name: userId
          in: path
          description: user id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: number
                height:
                  type: number
                weight:
                  type: number
                activity:
                  type: string
                food_type:
                  type: string
      responses:
        "200":
          description: Success update user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  statusCode:
                    type: number
                  message:
                    type: string

  /prediction:
    post:
      security:
        - UserAuth: []
      tags:
        - "ML API"
      summary: Do prediction from user food image
      requestBody:
        content:
          application/json:
            schema:
              properties:
                image:
                  type: string
      responses:
        "200":
          description: Success do nutrition food prediction
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  statusCode:
                    type: number
                  food_data:
                    type: object
                    properties:
                      name:
                        type: string
                      serving:
                        type: number
                      calorie:
                        type: number
                      fat:
                        type: number
                      protein:
                        type: number
                      carbohydrate:
                        type: number
                      description:
                        type: string
  /recomendation/{userId}:
    get:
      security:
        - UserAuth: []
      tags:
        - "ML API"
      summary: Get user food recomendation
      parameters:
        - name: userId
          in: path
          description: user id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success get list of food recomendation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  statusCode:
                    type: number
                  food_list:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        image:
                          type: string
                        calorie:
                          type: number
                        fat:
                          type: number
                        protein:
                          type: number
                        carbohydrate:
                          type: number
                        keywoard:
                          type: string
                        food_category:
                          type: string

components:
  securitySchemes:
    UserAuth:
      type: apiKey
      in: header
      name: X-API-TOKEN
      description: "Enter the token with the `Bearer ` prefix, e.g. Bearer abcde12345"
    UserGoogleAuth:
      type: apiKey
      in: header
      name: X-GOOGLE-API-KEY
      description: Enter the token you got from firebase while doing auth with google
  schemas:
    LoginResponse:
      type: object
      properties:
        status:
          type: boolean
        statusCode:
          type: number
        message:
          type: string
        data:
          type: object
          properties:
            userId:
              type: string
            accessToken:
              type: string
            refreshToken:
              type: string
    RegisterResponse:
      type: object
      properties:
        status:
          type: boolean
        statusCode:
          type: number
        message:
          type: string
